=== NiravGoyani12/codebackup-reciservices/creditcheck-clients/src/main/java/resources/CrifGate_Request_Invoke.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 (x64) (http://www.altova.com) by Vincenzo Iafelice (Crif SpA) -->
<xs:schema xmlns:cg="urn:crif-CrifGate:2:1" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="urn:crif-CrifGate:2:1" targetNamespace="urn:crif-CrifGate:2:1" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CG_Req_Invoke">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="OBO" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="orgcode" type="xs:string" use="required"/>
						<xs:attribute name="branchcode" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Auth">
					<xs:complexType>
						<xs:attribute name="orgcode" type="xs:string" use="optional"/>
						<xs:attribute name="usr" type="xs:string" use="required"/>
						<xs:attribute name="pwd" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Request">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Content" type="xs:string"/>
							<xs:element name="Params">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Param">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ServiceID" type="xs:string"/>
													<xs:element name="ProcessID" type="xs:string"/>
													<xs:element name="ForceRequest" type="xs:boolean" minOccurs="0"/>
													<xs:element name="NDG" type="xs:string" minOccurs="0"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="DosID" type="xs:string"/>
			<xs:attribute name="Sync" type="xs:string"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== NiravGoyani12/codebackup-reciservices/creditcheck-clients/src/main/java/resources/CrifGate_Request_Invoke.xml
<?xml version="1.0" encoding="UTF-8"?>
<cg:CG_Req_Invoke xmlns:cg="urn:crif-CrifGate:2:1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:crif-CrifGate:2:1 CrifGate_Request_Invoke.xsd ">
  <cg:Auth pwd="" usr=""/>
  <cg:Request>
    <cg:Content>cg:Content</cg:Content>
    <cg:Params>
      <cg:Param>
        <cg:ServiceID>cg:ServiceID</cg:ServiceID>
        <cg:ProcessID>cg:ProcessID</cg:ProcessID>
      </cg:Param>
    </cg:Params>
  </cg:Request>
</cg:CG_Req_Invoke>
